locatedInCR(lebanon,asia).
locatedInCR(solomon_islands,oceania).
locatedInCR(united_states_virgin_islands,americas).
locatedInCR(australia,oceania).
locatedInCR(greenland,americas).
locatedInCR(barbados,americas).
locatedInCR(vietnam,asia).
locatedInCR(syria,asia).
locatedInCR(american_samoa,oceania).
locatedInCR(svalbard_and_jan_mayen,europe).
locatedInCR(maldives,asia).
locatedInCR(guinea_bissau,africa).
locatedInCR(republic_of_the_congo,africa).
locatedInCR(vatican_city,europe).
locatedInCR(falkland_islands,americas).
locatedInCR(madagascar,africa).
locatedInCR(grenada,americas).
locatedInCR(portugal,europe).
locatedInCR(singapore,asia).
locatedInCR(sint_maarten,americas).
locatedInCR(swaziland,africa).
locatedInCR(philippines,asia).
locatedInCR(turks_and_caicos_islands,americas).
locatedInCR(finland,europe).
locatedInCR(puerto_rico,americas).
locatedInCR(faroe_islands,europe).
locatedInCR(reunion,africa).
locatedInCR(cook_islands,oceania).
locatedInCR(bahamas,americas).
locatedInCR(new_caledonia,oceania).
locatedInCR(canada,americas).
locatedInCR(dominica,americas).
locatedInCR(cocos_keeling_islands,oceania).
locatedInCR(cape_verde,africa).
locatedInCR(guam,oceania).
locatedInCR(guadeloupe,americas).
locatedInCR(saint_pierre_and_miquelon,americas).
locatedInCR(mayotte,africa).
locatedInCR(samoa,oceania).
locatedInCR(nepal,asia).
locatedInCR(norway,europe).
locatedInCR(wallis_and_futuna,oceania).
locatedInCR(aland_islands,europe).
locatedInCR(comoros,africa).
locatedInCR(martinique,americas).
locatedInCR(new_zealand,oceania).
locatedInCR(ireland,europe).
locatedInCR(guernsey,europe).
locatedInCR(tuvalu,oceania).
locatedInCR(haiti,americas).
locatedInCR(hong_kong,asia).
locatedInCR(isle_of_man,europe).
locatedInCR(san_marino,europe).
locatedInCR(trinidad_and_tobago,americas).
locatedInCR(montserrat,americas).
locatedInCR(niue,oceania).
locatedInCR(united_states_minor_outlying_islands,americas).
locatedInCR(tonga,oceania).
locatedInCR(british_virgin_islands,americas).
locatedInCR(japan,asia).
locatedInCR(iceland,europe).
locatedInCR(gibraltar,europe).
locatedInCR(antigua_and_barbuda,americas).
locatedInCR(bahrain,asia).
locatedInCR(cuba,americas).
locatedInCR(tunisia,africa).
locatedInCR(saint_martin,americas).
locatedInCR(saint_lucia,americas).
locatedInCR(south_georgia,americas).
locatedInCR(sweden,europe).
locatedInCR(sao_tome_and_principe,africa).
locatedInCR(anguilla,americas).
locatedInCR(norfolk_island,oceania).
locatedInCR(andorra,europe).
locatedInCR(saint_vincent_and_the_grenadines,americas).
locatedInCR(malta,europe).
locatedInCR(saint_barthelemy,americas).
locatedInCR(pitcairn_islands,oceania).
locatedInCR(tokelau,oceania).
locatedInCR(panama,americas).
locatedInCR(palau,oceania).
locatedInCR(french_polynesia,oceania).
locatedInCR(british_indian_ocean_territory,africa).
locatedInCR(fiji,oceania).
locatedInCR(saint_kitts_and_nevis,americas).
locatedInCR(moldova,europe).
locatedInCR(equatorial_guinea,africa).
locatedInCR(central_african_republic,africa).
locatedInCR(mauritius,africa).
locatedInCR(mongolia,asia).
locatedInCR(jersey,europe).
locatedInCR(eritrea,africa).
locatedInCR(taiwan,asia).
locatedInCR(curacao,americas).
locatedInCR(greece,europe).
locatedInCR(aruba,americas).
locatedInCR(marshall_islands,oceania).
locatedInCR(cayman_islands,americas).
locatedInCR(french_guiana,americas).
locatedInCR(gabon,africa).
locatedInCR(northern_mariana_islands,oceania).
locatedInCR(christmas_island,oceania).
locatedInCR(nauru,oceania).
locatedInCR(dominican_republic,americas).
locatedInCR(vanuatu,oceania).
locatedInCR(seychelles,africa).
locatedInCR(kiribati,oceania).
locatedInCR(nicaragua,americas).
locatedInCR(mali,africa).
locatedInCR(brunei,asia).
locatedInCR(jamaica,americas).
locatedInCR(costa_rica,americas).
neighborOf(norway,russia).
neighborOf(kuwait,iraq).
neighborOf(turkmenistan,kazakhstan).
neighborOf(afghanistan,turkmenistan).
neighborOf(mali,mauritania).
neighborOf(pakistan,iran).
neighborOf(myanmar,india).
neighborOf(hungary,romania).
neighborOf(morocco,western_sahara).
neighborOf(serbia,montenegro).
neighborOf(yemen,saudi_arabia).
neighborOf(costa_rica,panama).
neighborOf(austria,hungary).
neighborOf(south_sudan,central_african_republic).
neighborOf(central_african_republic,south_sudan).
neighborOf(belgium,netherlands).
neighborOf(china,nepal).
neighborOf(malawi,mozambique).
neighborOf(burundi,dr_congo).
neighborOf(china,north_korea).
neighborOf(romania,serbia).
neighborOf(dr_congo,rwanda).
neighborOf(france,luxembourg).
neighborOf(slovenia,austria).
neighborOf(senegal,gambia).
neighborOf(austria,liechtenstein).
neighborOf(tajikistan,afghanistan).
neighborOf(south_africa,namibia).
neighborOf(portugal,spain).
neighborOf(lebanon,syria).
neighborOf(laos,china).
neighborOf(dominican_republic,haiti).
neighborOf(zimbabwe,zambia).
neighborOf(republic_of_the_congo,central_african_republic).
neighborOf(uganda,dr_congo).
neighborOf(china,macau).
neighborOf(burkina_faso,mali).
neighborOf(rwanda,dr_congo).
neighborOf(tanzania,dr_congo).
neighborOf(luxembourg,belgium).
neighborOf(thailand,myanmar).
neighborOf(austria,italy).
neighborOf(russia,poland).
neighborOf(swaziland,south_africa).
neighborOf(kenya,somalia).
neighborOf(ecuador,colombia).
neighborOf(russia,georgia).
neighborOf(sudan,central_african_republic).
neighborOf(mali,algeria).
neighborOf(sint_maarten,saint_martin).
neighborOf(ghana,togo).
neighborOf(poland,lithuania).
neighborOf(burkina_faso,ghana).
neighborOf(romania,moldova).
neighborOf(israel,syria).
neighborOf(honduras,nicaragua).
neighborOf(serbia,kosovo).
neighborOf(somalia,kenya).
neighborOf(oman,saudi_arabia).
neighborOf(rwanda,uganda).
neighborOf(mozambique,zimbabwe).
neighborOf(afghanistan,india).
neighborOf(lithuania,latvia).
neighborOf(ukraine,slovakia).
neighborOf(colombia,brazil).
neighborOf(namibia,botswana).
neighborOf(india,bhutan).
neighborOf(benin,burkina_faso).
neighborOf(croatia,montenegro).
neighborOf(cyprus,united_kingdom).
neighborOf(iraq,syria).
neighborOf(libya,algeria).
neighborOf(uzbekistan,afghanistan).
neighborOf(malawi,tanzania).
neighborOf(south_africa,zimbabwe).
neighborOf(nigeria,cameroon).
neighborOf(montenegro,croatia).
neighborOf(iraq,turkey).
neighborOf(mozambique,malawi).
neighborOf(croatia,slovenia).
neighborOf(kenya,south_sudan).
neighborOf(malaysia,thailand).
neighborOf(nigeria,benin).
neighborOf(angola,republic_of_the_congo).
neighborOf(saudi_arabia,qatar).
neighborOf(malaysia,brunei).
neighborOf(egypt,sudan).
neighborOf(argentina,brazil).
neighborOf(guinea_bissau,guinea).
neighborOf(china,laos).
neighborOf(lebanon,israel).
neighborOf(lithuania,poland).
neighborOf(turkmenistan,iran).
neighborOf(brazil,peru).
neighborOf(dr_congo,south_sudan).
neighborOf(china,kyrgyzstan).
neighborOf(mozambique,tanzania).
neighborOf(guinea,sierra_leone).
neighborOf(zambia,dr_congo).
neighborOf(vatican_city,italy).
neighborOf(mongolia,china).
neighborOf(cameroon,equatorial_guinea).
neighborOf(niger,mali).
neighborOf(north_korea,russia).
neighborOf(canada,united_states).
neighborOf(germany,luxembourg).
neighborOf(iraq,kuwait).
neighborOf(israel,jordan).
neighborOf(mexico,united_states).
neighborOf(angola,zambia).
neighborOf(ethiopia,eritrea).
neighborOf(vietnam,cambodia).
neighborOf(guatemala,belize).
neighborOf(sierra_leone,liberia).
neighborOf(greece,bulgaria).
neighborOf(argentina,uruguay).
neighborOf(panama,costa_rica).
neighborOf(guinea,ivory_coast).
neighborOf(libya,egypt).
neighborOf(south_sudan,sudan).
neighborOf(belarus,lithuania).
neighborOf(belgium,luxembourg).
neighborOf(sudan,egypt).
neighborOf(chad,libya).
neighborOf(poland,belarus).
neighborOf(thailand,malaysia).
neighborOf(iraq,jordan).
neighborOf(indonesia,timor_leste).
neighborOf(liberia,guinea).
neighborOf(somalia,djibouti).
neighborOf(nepal,india).
neighborOf(iraq,saudi_arabia).
neighborOf(italy,slovenia).
neighborOf(saudi_arabia,jordan).
neighborOf(bulgaria,turkey).
neighborOf(tanzania,burundi).
neighborOf(libya,sudan).
neighborOf(spain,france).
neighborOf(russia,lithuania).
neighborOf(slovakia,austria).
neighborOf(israel,palestine).
neighborOf(pakistan,india).
neighborOf(armenia,georgia).
neighborOf(israel,lebanon).
neighborOf(republic_of_the_congo,angola).
neighborOf(republic_of_the_congo,cameroon).
neighborOf(dr_congo,tanzania).
neighborOf(ivory_coast,liberia).
neighborOf(kazakhstan,uzbekistan).
neighborOf(cameroon,republic_of_the_congo).
neighborOf(poland,russia).
neighborOf(honduras,guatemala).
neighborOf(laos,thailand).
neighborOf(finland,sweden).
neighborOf(tanzania,zambia).
neighborOf(ukraine,moldova).
neighborOf(india,sri_lanka).
neighborOf(greece,turkey).
neighborOf(netherlands,germany).
neighborOf(india,pakistan).
neighborOf(liechtenstein,switzerland).
neighborOf(france,germany).
neighborOf(uzbekistan,tajikistan).
neighborOf(guinea,senegal).
neighborOf(central_african_republic,dr_congo).
neighborOf(central_african_republic,chad).
neighborOf(sri_lanka,india).
neighborOf(togo,benin).
neighborOf(algeria,mauritania).
neighborOf(romania,hungary).
neighborOf(djibouti,eritrea).
neighborOf(mali,senegal).
neighborOf(palestine,israel).
neighborOf(bosnia_and_herzegovina,serbia).
neighborOf(oman,yemen).
neighborOf(brazil,venezuela).
neighborOf(latvia,lithuania).
neighborOf(burkina_faso,niger).
neighborOf(greece,albania).
neighborOf(bolivia,brazil).
neighborOf(bulgaria,greece).
neighborOf(croatia,serbia).
neighborOf(france,switzerland).
neighborOf(botswana,zambia).
neighborOf(india,nepal).
neighborOf(mozambique,south_africa).
neighborOf(nepal,china).
neighborOf(spain,andorra).
neighborOf(argentina,bolivia).
neighborOf(iran,iraq).
neighborOf(france,monaco).
neighborOf(tunisia,libya).
neighborOf(north_korea,south_korea).
neighborOf(bangladesh,india).
neighborOf(brazil,guyana).
neighborOf(algeria,tunisia).
neighborOf(djibouti,ethiopia).
neighborOf(french_guiana,brazil).
neighborOf(italy,san_marino).
neighborOf(costa_rica,nicaragua).
neighborOf(hungary,croatia).
neighborOf(eritrea,djibouti).
neighborOf(pakistan,china).
neighborOf(serbia,bosnia_and_herzegovina).
neighborOf(germany,poland).
neighborOf(macedonia,bulgaria).
neighborOf(mauritania,algeria).
neighborOf(guinea,liberia).
neighborOf(switzerland,austria).
neighborOf(bulgaria,macedonia).
neighborOf(italy,switzerland).
neighborOf(south_korea,north_korea).
neighborOf(mali,burkina_faso).
neighborOf(sweden,norway).
neighborOf(turkey,georgia).
neighborOf(latvia,estonia).
neighborOf(ukraine,poland).
neighborOf(gabon,equatorial_guinea).
neighborOf(india,china).
neighborOf(niger,chad).
neighborOf(algeria,libya).
neighborOf(belarus,russia).
neighborOf(greece,macedonia).
neighborOf(egypt,libya).
neighborOf(albania,greece).
neighborOf(uganda,rwanda).
neighborOf(benin,niger).
neighborOf(venezuela,guyana).
neighborOf(ethiopia,somalia).
neighborOf(iran,afghanistan).
neighborOf(oman,united_arab_emirates).
neighborOf(kenya,uganda).
neighborOf(jordan,iraq).
neighborOf(togo,burkina_faso).
neighborOf(tanzania,uganda).
neighborOf(albania,macedonia).
neighborOf(peru,brazil).
neighborOf(central_african_republic,republic_of_the_congo).
neighborOf(italy,vatican_city).
neighborOf(turkey,iraq).
neighborOf(vietnam,china).
neighborOf(georgia,russia).
neighborOf(croatia,bosnia_and_herzegovina).
neighborOf(north_korea,china).
neighborOf(slovakia,ukraine).
neighborOf(switzerland,germany).
neighborOf(belgium,germany).
neighborOf(cameroon,chad).
neighborOf(brunei,malaysia).
neighborOf(germany,czechia).
neighborOf(botswana,south_africa).
neighborOf(lesotho,south_africa).
neighborOf(norway,finland).
neighborOf(suriname,brazil).
neighborOf(uzbekistan,kazakhstan).
neighborOf(zimbabwe,botswana).
neighborOf(brazil,paraguay).
neighborOf(latvia,belarus).
neighborOf(libya,tunisia).
neighborOf(chad,south_sudan).
neighborOf(laos,myanmar).
neighborOf(republic_of_the_congo,gabon).
neighborOf(algeria,western_sahara).
neighborOf(ethiopia,south_sudan).
neighborOf(sudan,eritrea).
neighborOf(gabon,republic_of_the_congo).
neighborOf(germany,switzerland).
neighborOf(paraguay,brazil).
neighborOf(colombia,panama).
neighborOf(thailand,cambodia).
neighborOf(mauritania,western_sahara).
neighborOf(ukraine,hungary).
neighborOf(syria,iraq).
neighborOf(mexico,belize).
neighborOf(france,spain).
neighborOf(italy,france).
neighborOf(macedonia,albania).
neighborOf(germany,denmark).
neighborOf(albania,montenegro).
neighborOf(chile,peru).
neighborOf(montenegro,albania).
neighborOf(south_sudan,ethiopia).
neighborOf(gambia,senegal).
neighborOf(senegal,guinea).
neighborOf(spain,gibraltar).
neighborOf(china,myanmar).
neighborOf(serbia,hungary).
neighborOf(united_arab_emirates,saudi_arabia).
neighborOf(sudan,libya).
neighborOf(djibouti,somalia).
neighborOf(latvia,russia).
neighborOf(colombia,peru).
neighborOf(zambia,angola).
neighborOf(haiti,dominican_republic).
neighborOf(qatar,saudi_arabia).
neighborOf(vietnam,laos).
neighborOf(macedonia,greece).
neighborOf(bolivia,argentina).
neighborOf(nicaragua,costa_rica).
neighborOf(russia,kazakhstan).
neighborOf(india,bangladesh).
neighborOf(slovenia,italy).
neighborOf(russia,norway).
neighborOf(armenia,iran).
neighborOf(brazil,uruguay).
neighborOf(sudan,ethiopia).
neighborOf(tanzania,mozambique).
neighborOf(guatemala,honduras).
neighborOf(spain,morocco).
neighborOf(hungary,austria).
neighborOf(saudi_arabia,kuwait).
neighborOf(tajikistan,china).
neighborOf(venezuela,brazil).
neighborOf(azerbaijan,georgia).
neighborOf(mozambique,zambia).
neighborOf(kazakhstan,russia).
neighborOf(swaziland,mozambique).
neighborOf(hong_kong,china).
neighborOf(albania,kosovo).
neighborOf(namibia,south_africa).
neighborOf(kazakhstan,kyrgyzstan).
neighborOf(ethiopia,kenya).
neighborOf(estonia,russia).
neighborOf(kuwait,saudi_arabia).
neighborOf(niger,algeria).
neighborOf(guyana,venezuela).
neighborOf(luxembourg,germany).
neighborOf(ukraine,romania).
neighborOf(western_sahara,algeria).
neighborOf(croatia,hungary).
neighborOf(dr_congo,republic_of_the_congo).
neighborOf(cameroon,central_african_republic).
neighborOf(mauritania,senegal).
neighborOf(norway,sweden).
neighborOf(senegal,mali).
neighborOf(serbia,croatia).
neighborOf(senegal,guinea_bissau).
neighborOf(serbia,romania).
neighborOf(germany,france).
neighborOf(uruguay,brazil).
neighborOf(central_african_republic,sudan).
neighborOf(afghanistan,tajikistan).
neighborOf(burkina_faso,ivory_coast).
neighborOf(ivory_coast,burkina_faso).
neighborOf(guatemala,mexico).
neighborOf(dr_congo,burundi).
neighborOf(san_marino,italy).
neighborOf(slovakia,poland).
neighborOf(peru,ecuador).
neighborOf(hungary,slovakia).
neighborOf(switzerland,france).
neighborOf(peru,bolivia).
neighborOf(uganda,tanzania).
neighborOf(belgium,france).
neighborOf(burkina_faso,benin).
neighborOf(montenegro,bosnia_and_herzegovina).
neighborOf(rwanda,tanzania).
neighborOf(spain,portugal).
neighborOf(yemen,oman).
neighborOf(algeria,morocco).
neighborOf(romania,bulgaria).
neighborOf(moldova,ukraine).
neighborOf(bhutan,china).
neighborOf(equatorial_guinea,cameroon).
neighborOf(tajikistan,kyrgyzstan).
neighborOf(peru,colombia).
neighborOf(dr_congo,zambia).
neighborOf(mexico,guatemala).
neighborOf(russia,azerbaijan).
neighborOf(bulgaria,serbia).
neighborOf(georgia,azerbaijan).
neighborOf(russia,estonia).
neighborOf(russia,north_korea).
neighborOf(bulgaria,romania).
neighborOf(china,afghanistan).
neighborOf(kenya,ethiopia).
neighborOf(zambia,mozambique).
neighborOf(mali,guinea).
neighborOf(paraguay,bolivia).
neighborOf(morocco,spain).
neighborOf(bosnia_and_herzegovina,croatia).
neighborOf(colombia,venezuela).
neighborOf(indonesia,malaysia).
neighborOf(turkey,iran).
neighborOf(zambia,zimbabwe).
neighborOf(french_guiana,suriname).
neighborOf(kosovo,macedonia).
neighborOf(niger,nigeria).
neighborOf(mali,niger).
neighborOf(paraguay,argentina).
neighborOf(laos,vietnam).
neighborOf(argentina,chile).
neighborOf(poland,slovakia).
neighborOf(cambodia,vietnam).
neighborOf(macedonia,kosovo).
neighborOf(syria,jordan).
neighborOf(france,italy).
neighborOf(montenegro,kosovo).
neighborOf(poland,germany).
neighborOf(brazil,colombia).
neighborOf(eritrea,sudan).
neighborOf(belarus,latvia).
neighborOf(russia,china).
neighborOf(jordan,palestine).
neighborOf(kyrgyzstan,tajikistan).
neighborOf(slovakia,czechia).
neighborOf(ukraine,belarus).
neighborOf(ethiopia,djibouti).
neighborOf(uzbekistan,kyrgyzstan).
neighborOf(honduras,el_salvador).
neighborOf(china,vietnam).
neighborOf(burundi,rwanda).
neighborOf(austria,slovakia).
neighborOf(afghanistan,uzbekistan).
neighborOf(poland,czechia).
neighborOf(russia,belarus).
neighborOf(austria,germany).
neighborOf(kosovo,montenegro).
neighborOf(angola,namibia).
neighborOf(cameroon,nigeria).
neighborOf(guinea,mali).
neighborOf(russia,latvia).
neighborOf(united_kingdom,cyprus).
neighborOf(guinea,guinea_bissau).
neighborOf(hungary,ukraine).
neighborOf(germany,netherlands).
neighborOf(zambia,tanzania).
neighborOf(niger,benin).
neighborOf(tanzania,rwanda).
neighborOf(china,hong_kong).
neighborOf(hungary,serbia).
neighborOf(turkmenistan,afghanistan).
neighborOf(venezuela,colombia).
neighborOf(luxembourg,france).
neighborOf(sudan,south_sudan).
neighborOf(ukraine,russia).
neighborOf(austria,czechia).
neighborOf(finland,russia).
neighborOf(guyana,brazil).
neighborOf(syria,lebanon).
neighborOf(united_arab_emirates,oman).
neighborOf(belarus,poland).
neighborOf(romania,ukraine).
neighborOf(palestine,egypt).
neighborOf(uzbekistan,turkmenistan).
neighborOf(saudi_arabia,iraq).
neighborOf(armenia,turkey).
neighborOf(dr_congo,angola).
neighborOf(chad,niger).
neighborOf(egypt,palestine).
neighborOf(austria,switzerland).
neighborOf(namibia,zambia).
neighborOf(zambia,botswana).
neighborOf(united_kingdom,ireland).
neighborOf(guatemala,el_salvador).
neighborOf(iran,turkey).
neighborOf(india,myanmar).
neighborOf(iran,pakistan).
neighborOf(dr_congo,uganda).
neighborOf(poland,ukraine).
neighborOf(uruguay,argentina).
neighborOf(ghana,ivory_coast).
neighborOf(thailand,laos).
neighborOf(sierra_leone,guinea).
neighborOf(south_sudan,kenya).
neighborOf(saudi_arabia,yemen).
neighborOf(brazil,suriname).
neighborOf(turkey,bulgaria).
neighborOf(togo,ghana).
neighborOf(kazakhstan,china).
neighborOf(kyrgyzstan,uzbekistan).
neighborOf(china,tajikistan).
neighborOf(lithuania,belarus).
neighborOf(armenia,azerbaijan).
neighborOf(bosnia_and_herzegovina,montenegro).
neighborOf(afghanistan,pakistan).
neighborOf(azerbaijan,iran).
neighborOf(turkey,armenia).
neighborOf(malawi,zambia).
neighborOf(slovenia,hungary).
neighborOf(switzerland,liechtenstein).
neighborOf(liberia,sierra_leone).
neighborOf(netherlands,belgium).
neighborOf(serbia,bulgaria).
neighborOf(equatorial_guinea,gabon).
neighborOf(france,belgium).
neighborOf(macedonia,serbia).
neighborOf(south_africa,mozambique).
neighborOf(montenegro,serbia).
neighborOf(bolivia,chile).
neighborOf(argentina,paraguay).
neighborOf(somalia,ethiopia).
neighborOf(chad,central_african_republic).
neighborOf(iran,azerbaijan).
neighborOf(nigeria,chad).
neighborOf(myanmar,china).
neighborOf(western_sahara,mauritania).
neighborOf(saudi_arabia,oman).
neighborOf(finland,norway).
neighborOf(switzerland,italy).
neighborOf(western_sahara,morocco).
neighborOf(belize,mexico).
neighborOf(liberia,ivory_coast).
neighborOf(georgia,armenia).
neighborOf(jordan,syria).
neighborOf(bhutan,india).
neighborOf(el_salvador,guatemala).
neighborOf(bangladesh,myanmar).
neighborOf(lithuania,russia).
neighborOf(cambodia,laos).
neighborOf(kyrgyzstan,kazakhstan).
neighborOf(uganda,south_sudan).
neighborOf(botswana,namibia).
neighborOf(laos,cambodia).
neighborOf(china,bhutan).
neighborOf(ivory_coast,guinea).
neighborOf(estonia,latvia).
neighborOf(liechtenstein,austria).
neighborOf(russia,finland).
neighborOf(suriname,french_guiana).
neighborOf(guinea_bissau,senegal).
neighborOf(niger,burkina_faso).
neighborOf(turkey,syria).
neighborOf(united_states,canada).
neighborOf(ireland,united_kingdom).
neighborOf(france,andorra).
neighborOf(hungary,slovenia).
neighborOf(china,russia).
neighborOf(saint_martin,sint_maarten).
neighborOf(gibraltar,spain).
neighborOf(dr_congo,central_african_republic).
neighborOf(nigeria,niger).
neighborOf(saudi_arabia,united_arab_emirates).
neighborOf(zimbabwe,south_africa).
neighborOf(azerbaijan,russia).
neighborOf(namibia,angola).
neighborOf(tanzania,malawi).
neighborOf(russia,mongolia).
neighborOf(brazil,french_guiana).
neighborOf(senegal,mauritania).
neighborOf(pakistan,afghanistan).
neighborOf(slovenia,croatia).
neighborOf(zambia,namibia).
neighborOf(georgia,turkey).
neighborOf(afghanistan,iran).
neighborOf(syria,turkey).
neighborOf(belarus,ukraine).
neighborOf(myanmar,laos).
neighborOf(kosovo,albania).
neighborOf(afghanistan,china).
neighborOf(burundi,tanzania).
neighborOf(belize,guatemala).
neighborOf(burkina_faso,togo).
neighborOf(malaysia,indonesia).
neighborOf(timor_leste,indonesia).
neighborOf(mozambique,swaziland).
neighborOf(turkey,azerbaijan).
neighborOf(kosovo,serbia).
neighborOf(algeria,niger).
neighborOf(botswana,zimbabwe).
neighborOf(kenya,tanzania).
neighborOf(ecuador,peru).
neighborOf(mali,ivory_coast).
neighborOf(andorra,france).
neighborOf(niger,libya).
neighborOf(india,afghanistan).
neighborOf(peru,chile).
neighborOf(central_african_republic,cameroon).
neighborOf(south_sudan,dr_congo).
neighborOf(italy,austria).
neighborOf(ghana,burkina_faso).
neighborOf(kazakhstan,turkmenistan).
neighborOf(iraq,iran).
neighborOf(south_sudan,chad).
neighborOf(south_africa,swaziland).
neighborOf(south_africa,botswana).
neighborOf(russia,ukraine).
neighborOf(benin,nigeria).
neighborOf(ivory_coast,mali).
neighborOf(panama,colombia).
neighborOf(rwanda,burundi).
neighborOf(uganda,kenya).
neighborOf(turkey,greece).
neighborOf(czechia,austria).
neighborOf(morocco,algeria).
neighborOf(tanzania,kenya).
neighborOf(papua_new_guinea,indonesia).
neighborOf(denmark,germany).
neighborOf(macau,china).
neighborOf(germany,belgium).
neighborOf(eritrea,ethiopia).
neighborOf(jordan,israel).
neighborOf(mongolia,russia).
neighborOf(austria,slovenia).
neighborOf(jordan,saudi_arabia).
neighborOf(moldova,romania).
neighborOf(andorra,spain).
neighborOf(republic_of_the_congo,dr_congo).
neighborOf(ivory_coast,ghana).
neighborOf(cameroon,gabon).
neighborOf(china,kazakhstan).
neighborOf(israel,egypt).
neighborOf(azerbaijan,armenia).
neighborOf(gabon,cameroon).
neighborOf(south_sudan,uganda).
neighborOf(myanmar,bangladesh).
neighborOf(czechia,poland).
neighborOf(chad,nigeria).
neighborOf(libya,chad).
neighborOf(chile,bolivia).
neighborOf(cambodia,thailand).
neighborOf(sudan,chad).
neighborOf(monaco,france).
neighborOf(bolivia,paraguay).
neighborOf(indonesia,papua_new_guinea).
neighborOf(colombia,ecuador).
neighborOf(brazil,bolivia).
neighborOf(benin,togo).
neighborOf(chile,argentina).
neighborOf(palestine,jordan).
neighborOf(algeria,mali).
neighborOf(chad,sudan).
neighborOf(turkmenistan,uzbekistan).
neighborOf(zambia,malawi).
neighborOf(kyrgyzstan,china).
neighborOf(tunisia,algeria).
neighborOf(serbia,macedonia).
neighborOf(mauritania,mali).
neighborOf(china,mongolia).
neighborOf(ethiopia,sudan).
neighborOf(brazil,argentina).
neighborOf(suriname,guyana).
neighborOf(syria,israel).
neighborOf(slovakia,hungary).
neighborOf(china,pakistan).
neighborOf(libya,niger).
neighborOf(china,india).
neighborOf(angola,dr_congo).
neighborOf(chad,cameroon).
neighborOf(czechia,slovakia).
neighborOf(nicaragua,honduras).
neighborOf(azerbaijan,turkey).
neighborOf(iran,turkmenistan).
neighborOf(sweden,finland).
neighborOf(zimbabwe,mozambique).
neighborOf(el_salvador,honduras).
neighborOf(tajikistan,uzbekistan).
neighborOf(egypt,israel).
neighborOf(czechia,germany).
neighborOf(bolivia,peru).
neighborOf(guyana,suriname).
neighborOf(myanmar,thailand).
neighborOf(south_africa,lesotho).
neighborOf(united_states,mexico).
neighborOf(iran,armenia).
neighborOf(germany,austria).
locatedInCR_with_depth(X, Z, Recursion, MaxDepth, Depth, Proof) :- Recursion =< MaxDepth, locatedInCR(X, Z), Depth = 1, Proof = [locatedInCR(X, Z)].
locatedInCR_with_depth(X, Z, Recursion, MaxDepth, Depth, Proof) :- Recursion < MaxDepth, neighborOf(X, Y), Next_Recursion is Recursion + 1, locatedInCR_with_depth(Y, Z, Next_Recursion, MaxDepth, SubDepth, SubProof), Depth is SubDepth + 1, Proof = [neighborOf(X, Y) | SubProof].
query_with_depth(X, Z, MaxDepth, Depths, Proofs) :- findall([Depth, Proof], locatedInCR_with_depth(X, Z, 0, MaxDepth, Depth, Proof), Results), findall(D, member([D, _], Results), Depths), findall(P, member([_, P], Results), Proofs).